#!/bin/bash
: << 'COMMENT' 
This is a simple script to clean /etc/hosts

COMMENT

function gREP() {
    grep -v $term /etc/hosts >> /tmp/hosts; mv /tmp/hosts /etc/hosts; tac /etc/hosts 
}

if [[ $(id -u) -ne "0" ]]; then
    printf "[error] You must run this as root... try sudo?" >&2
    exit 1
fi

printf "Info in /etc/hosts file:\n\n"
tac /etc/hosts
printf "\n"
read -p "Provide the host you would like to remove: " term
printf "\r\n"

gREP && printf "\n An attempt was made. \n"
